### PR TITLE
hooks and docs to enforce a maximum number of cycles

### PR DESCRIPTION
**Pull request by turadg**
Thanks for this plugin. It helped us detect a bunch of cycles. :)

As we knock out cycles, we want to ensure new ones aren't introduced. So we need to error, but can't go full `failOnError` until we get down to zero.

This PR adds hooks for start and end of the cycle detection, which can be used to set a max cycles policy. It also documents how in the README.

---
This change is [Reviewable](https://reviewable.io/reviews/aackerman/circular-dependency-plugin/27)

### CODE REVIEW

**Comment by aackerman** [comment]
I'm not seeing a strong need for `onStartDetecting` aside from having symmetry to `onEndDetecting` even in your example, the variable is initialized before the module and in `onStartDetecting`.

If you agree I would say go ahead and remove it. Even if you don't, I would like the methods renamed to `onStart` and `onEnd` before merging these changes.

**Comment by turadg** [comment]
> I'm not seeing a strong need for onStartDetecting aside from having symmetry to onEndDetecting

Is that not reason enough? :)

> even in your example, the variable is initialized before the module and in onStartDetecting.

I was thinking it needs to be reset on each start of detection. I use webpack-dev-server and I figured the module level would only run once.

> I would like the methods renamed to onStart and onEnd before merging these changes.

Will do.

**Comment by turadg** [comment]
I just rebased off upstream/master

**Comment by turadg** [comment]
@aackerman, are there any other blockers to merging?

**Comment by aackerman** [comment]
Published in version 4.4.0

**Pull request merged**
